import Head from "next/head";
import Header from "@/components/Header";
import SecaoCapa from "@/components/SecaoCapa";
import SecaoProdutos from "@/components/SecaoProdutos";
import SecaoSobre from "@/components/SecaoSobre";
import SecaoContato from "@/components/SecaoContato"
import Footer from "@/components/Footer";


export default function Home() {
  return (
    <>
      <Head>
        <title>Óticas vida - Loja de óculos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main>
        <SecaoCapa/>
        <SecaoProdutos/>
        <SecaoSobre />
        <SecaoContato />
      </main>
      <Footer />
    </>
  );
}
